[package]
name = "pingmon"
version = "0.1.0"
edition = "2021"

[dependencies]
argp = "0.3.0"
directories = "5.0.1"
env_logger = "0.11.3"
influxdb = { version = "0.7.1", default-features=false, features = ["derive", "serde", "curl-client"] }
log = "0.4.21"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
toml = "0.8.12"
tracert = "0.7.0"

[[bin]]
name = "pingmon"
path = "src/main.rs"

