[package]
name = "pingmon"
version = "0.1.0"
edition = "2021"

[dependencies]
influxdb = { version = "0.7.1", default-features=false, features = ["derive", "serde", "curl-client"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tracert = "0.7.0"
